"Resource/UI/SkillMenu.res"
{
	"skill"
	{
		"ControlName"		"CSkillMenu"
		"fieldName"		"skill"
		"xpos"			"0"
		"ypos"			"0"
		"wide"			"640"
		"tall"			"480"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"chooseSkill"
	{
		"ControlName"		"Label"
		"fieldName"		"chooseSkill"
		"xpos"		"76"
		"ypos"		"22"
		"wide"		"450"
		"tall"		"48"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"Choose Your Skills"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"	"0"
		"font"		"MenuTitle"
	}
	"skill1"
	{
		"ControlName"		"Button"
		"fieldName"		"skill1"
		"xpos"			"25"
		"ypos"			"106"
		"wide"			"200"
		"tall"			"20"
		"autoResize"		"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"3"
		"labelText"		"Upgrade Skill 1"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"command"		"upgradeskill 1"
	}
	"skill2"
	{
		"ControlName"		"Button"
		"fieldName"		"skill2"
		"xpos"			"25"
		"ypos"			"166"
		"wide"			"200"
		"tall"			"20"
		"autoResize"		"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"4"
		"labelText"		"Upgrade Skill 2"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"command"		"upgradeskill 2"
	}	
	"skill3"
	{
		"ControlName"		"Button"
		"fieldName"		"skill3"
		"xpos"			"25"
		"ypos"			"224"
		"wide"			"200"
		"tall"			"20"
		"autoResize"		"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"1"
		"labelText"		"Upgrade Skill 3"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"command"		"upgradeskill 3"
		"Default"		"1"
	}
	"skill4"
	{
		"ControlName"		"Button"
		"fieldName"		"skill4"
		"xpos"			"25"
		"ypos"			"284"
		"wide"			"200"
		"tall"			"20"
		"autoResize"		"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"2"
		"labelText"		"Upgrade Skill 4"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"command"		"upgradeskill 4"
	}
	"skill5"
	{
		"ControlName"		"Button"
		"fieldName"		"skill5"
		"xpos"			"25"
		"ypos"			"334"
		"wide"			"200"
		"tall"			"20"
		"autoResize"		"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"Upgrade Skill 5"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"Command"		"upgradeskill 5"
	}
	"CancelButton"
	{
		"ControlName"		"Button"
		"fieldName"		"CancelButton"
		"xpos"			"25"
		"ypos"			"366"
		"wide"			"148"
		"tall"			"20"
		"autoResize"		"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#TM_Cancel"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"Command"		"vguicancel"
	}
	"Skill1Text"
	{
		"ControlName"		"RichText"
		"fieldName"		"Skill1Text"
		"xpos"		"230"
		"ypos"		"106"
		"wide"		"339"
		"tall"		"50"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"text"		""
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"1"
	}
	"Skill2Text"
	{
		"ControlName"		"RichText"
		"fieldName"		"Skill2Text"
		"xpos"		"230"
		"ypos"		"166"
		"wide"		"339"
		"tall"		"50"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"text"		""
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"1"
	}
	"Skill3Text"
	{
		"ControlName"		"RichText"
		"fieldName"		"Skill3Text"
		"xpos"		"230"
		"ypos"		"224"
		"wide"		"339"
		"tall"		"50"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"text"		""
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
	}
	"Skill4Text"
	{
		"ControlName"		"RichText"
		"fieldName"		"Skill4Text"
		"xpos"		"230"
		"ypos"		"284"
		"wide"		"339"
		"tall"		"50"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"text"		""
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
	}
}